package com.ssafy.ssabangpalbang.review.repository;

import com.ssafy.ssabangpalbang.review.domain.MemberReview;
import com.ssafy.ssabangpalbang.review.repository.projection.MemberReviewTagCountRow;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.PageRequest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DataJpaTest
@ActiveProfiles("test")
@Sql(statements = {
        "DROP TABLE IF EXISTS member_review_tag",
        "DROP TABLE IF EXISTS member_review",
        "CREATE TABLE member_review ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "study_id BIGINT NOT NULL, "
                + "reviewer_id BIGINT NOT NULL, "
                + "reviewee_id BIGINT NOT NULL, "
                + "rating INTEGER CHECK (rating BETWEEN 1 AND 5), "
                + "liked BOOLEAN NOT NULL DEFAULT FALSE, "
                + "content VARCHAR(500), "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "
                + "CONSTRAINT ck_member_review_not_self "
                + "CHECK (reviewer_id <> reviewee_id), "
                + "CONSTRAINT uq_member_review_study_reviewer_reviewee "
                + "UNIQUE (study_id, reviewer_id, reviewee_id))",
        "CREATE TABLE member_review_tag ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "review_id BIGINT NOT NULL, "
                + "tag_code VARCHAR(40) NOT NULL, "
                + "CONSTRAINT uq_member_review_tag "
                + "UNIQUE (review_id, tag_code))"
})
@Sql(
        statements = {
                "DROP TABLE IF EXISTS member_review_tag",
                "DROP TABLE IF EXISTS member_review"
        },
        executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD
)
class MemberReviewRepositoryTest {

    @Autowired MemberReviewRepository memberReviewRepository;
    @Autowired MemberReviewTagRepository memberReviewTagRepository;
    @Autowired JdbcTemplate jdbcTemplate;

    @Test
    void 스터디_평가자_대상_조합은_한_번만_저장된다() {
        memberReviewRepository.saveAndFlush(
                MemberReview.create(10L, 7L, 9L, true, "첫 평가")
        );

        assertThat(memberReviewRepository
                .existsByStudyIdAndReviewerIdAndRevieweeId(10L, 7L, 9L))
                .isTrue();
        assertThatThrownBy(() -> memberReviewRepository.saveAndFlush(
                MemberReview.create(10L, 7L, 9L, false, "중복 평가")
        )).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void DB도_본인_평가를_거절한다() {
        assertThatThrownBy(() -> memberReviewRepository.saveAndFlush(
                MemberReview.create(10L, 7L, 7L, true, null)
        )).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void 대상_회원의_평가_수_좋아요_수_태그를_집계한다() {
        insertReview(30L, 10L, 7L, 9L, true, "2026-08-03T13:30:00Z");
        insertReview(20L, 11L, 8L, 9L, false, "2026-08-03T13:20:00Z");
        insertReview(10L, 12L, 11L, 9L, true, "2026-08-03T13:20:00Z");
        insertTag(30L, "PUNCTUAL");
        insertTag(30L, "GOOD_RECORDS");
        insertTag(20L, "PUNCTUAL");

        assertThat(memberReviewRepository.countByRevieweeId(9L))
                .isEqualTo(3L);
        assertThat(memberReviewRepository.countByRevieweeIdAndLikedTrue(9L))
                .isEqualTo(2L);

        List<MemberReviewTagCountRow> tagCounts =
                memberReviewRepository.aggregateTagCountsByRevieweeId(9L);
        assertThat(tagCounts).extracting(MemberReviewTagCountRow::getTagCode)
                .containsExactly("PUNCTUAL", "GOOD_RECORDS");
        assertThat(tagCounts.get(0).getTagCount()).isEqualTo(2L);
        assertThat(tagCounts.get(1).getTagCount()).isEqualTo(1L);
    }

    @Test
    void 시각과_ID_커서로_최신순_페이지를_조회하고_태그를_일괄_조회한다() {
        insertReview(30L, 10L, 7L, 9L, true, "2026-08-03T13:30:00Z");
        insertReview(20L, 11L, 8L, 9L, false, "2026-08-03T13:20:00Z");
        insertReview(10L, 12L, 11L, 9L, false, "2026-08-03T13:20:00Z");
        insertReview(40L, 13L, 10L, 9L, false, "2026-08-03T13:10:00Z");
        insertTag(30L, "PUNCTUAL");

        var first = memberReviewRepository.findFirstPageByRevieweeId(
                9L,
                PageRequest.of(0, 3)
        );
        var next = memberReviewRepository.findNextPageByRevieweeId(
                9L,
                first.get(1).getCreatedAt(),
                first.get(1).getId(),
                PageRequest.of(0, 3)
        );

        assertThat(first).extracting(MemberReview::getId)
                .containsExactly(30L, 20L, 10L);
        assertThat(next).extracting(MemberReview::getId)
                .containsExactly(10L, 40L);
        assertThat(memberReviewTagRepository
                .findByReviewIdIn(List.of(30L, 20L)))
                .extracting("tagCode")
                .containsExactly("PUNCTUAL");
    }

    @Test
    void 스터디에서_평가자가_이미_평가한_대상_ID만_조회한다() {
        insertReview(10L, 31L, 7L, 9L, true, "2026-08-03T13:20:00Z");
        insertReview(20L, 31L, 7L, 12L, true, "2026-08-03T13:30:00Z");
        insertReview(30L, 31L, 8L, 13L, false, "2026-08-03T13:40:00Z");
        insertReview(40L, 32L, 7L, 14L, false, "2026-08-03T13:50:00Z");

        assertThat(memberReviewRepository
                .findRevieweeIdsByStudyIdAndReviewerId(31L, 7L))
                .containsExactlyInAnyOrder(9L, 12L);
    }

    private void insertReview(
            Long id,
            Long studyId,
            Long reviewerId,
            Long revieweeId,
            boolean liked,
            String createdAt
    ) {
        jdbcTemplate.update("""
                INSERT INTO member_review (
                    id, study_id, reviewer_id, reviewee_id,
                    rating, liked, content, created_at
                ) VALUES (?, ?, ?, ?, NULL, ?, '리뷰', CAST(? AS TIMESTAMP WITH TIME ZONE))
                """,
                id,
                studyId,
                reviewerId,
                revieweeId,
                liked,
                createdAt
        );
    }

    private void insertTag(Long reviewId, String tagCode) {
        jdbcTemplate.update("""
                INSERT INTO member_review_tag (review_id, tag_code)
                VALUES (?, ?)
                """,
                reviewId,
                tagCode
        );
    }
}
