package com.ssafy.ssabangpalbang.community.service;

import com.ssafy.ssabangpalbang.community.dto.response.CommentDeleteResponse;
import com.ssafy.ssabangpalbang.community.repository.CommentCommandRepositoryImpl;
import com.ssafy.ssabangpalbang.community.repository.CommentQueryRepository;
import com.ssafy.ssabangpalbang.community.repository.PostQueryRepository;
import com.ssafy.ssabangpalbang.community.repository.projection.CommentPostMetricsRow;
import com.ssafy.ssabangpalbang.community.repository.projection.CommentSnapshot;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Clock;
import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.when;

@DataJpaTest
@ActiveProfiles("test")
@Import({
        CommentCommandService.class,
        CommentCommandRepositoryImpl.class
})
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@Sql(statements = {
        "DROP TABLE IF EXISTS post_comment",
        "DROP TABLE IF EXISTS post",
        "DROP TABLE IF EXISTS member",
        "CREATE TABLE member ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "email VARCHAR(255) NOT NULL UNIQUE, "
                + "password_hash VARCHAR(255), "
                + "nickname VARCHAR(50) NOT NULL UNIQUE, "
                + "profile_image_url VARCHAR(500), "
                + "selected_character_id VARCHAR(20) NOT NULL "
                + "DEFAULT 'PALBANG', "
                + "age_group VARCHAR(20), "
                + "age_group_public_agreed BOOLEAN NOT NULL DEFAULT FALSE, "
                + "service_notification_agreed BOOLEAN NOT NULL DEFAULT TRUE, "
                + "ad_notification_agreed BOOLEAN NOT NULL DEFAULT FALSE, "
                + "status VARCHAR(20) NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE post ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "board_type VARCHAR(20) NOT NULL, "
                + "author_id BIGINT, "
                + "title VARCHAR(200) NOT NULL, "
                + "content CLOB NOT NULL, "
                + "status VARCHAR(20) NOT NULL, "
                + "is_auto_report BOOLEAN NOT NULL, "
                + "report_id BIGINT, "
                + "apartment_id BIGINT, "
                + "view_count BIGINT NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE post_comment ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "post_id BIGINT NOT NULL, "
                + "author_id BIGINT NOT NULL, "
                + "content CLOB NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)"
})
@Sql(
        statements = {
                "DROP TABLE IF EXISTS post_comment",
                "DROP TABLE IF EXISTS post",
                "DROP TABLE IF EXISTS member"
        },
        executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD
)
class CommentDeleteTransactionTest {

    private static final Instant NOW =
            Instant.parse("2026-07-25T08:25:00Z");

    @Autowired
    private CommentCommandService commentCommandService;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @MockitoBean
    private PostQueryRepository postQueryRepository;

    @MockitoBean
    private CommentQueryRepository commentQueryRepository;

    @MockitoBean
    private Clock clock;

    @Test
    void updatesOnlyDeleteTimestampsAndPreservesCommentData() {
        Long memberId = insertMember();
        Long postId = insertPost(memberId);
        Long commentId = insertComment(postId, memberId);
        Instant originalCreatedAt = currentInstant(
                "created_at",
                commentId
        );
        when(clock.instant()).thenReturn(NOW);
        when(commentQueryRepository.findSnapshot(commentId))
                .thenReturn(Optional.of(new CommentSnapshot(
                        commentId,
                        postId,
                        memberId,
                        null
                )));
        when(commentQueryRepository.findPostMetrics(postId))
                .thenReturn(Optional.of(new CommentPostMetricsRow(
                        true,
                        0L,
                        0L,
                        3L,
                        false,
                        new BigDecimal("17.70")
                )));

        CommentDeleteResponse response = commentCommandService.delete(
                memberId,
                commentId
        );

        assertThat(response.deletedAt().toInstant()).isEqualTo(NOW);
        assertThat(currentInstant("deleted_at", commentId))
                .isEqualTo(NOW);
        assertThat(currentInstant("updated_at", commentId))
                .isEqualTo(NOW);
        assertThat(currentInstant("created_at", commentId))
                .isEqualTo(originalCreatedAt);
        assertThat(currentLong("post_id", commentId))
                .isEqualTo(postId);
        assertThat(currentLong("author_id", commentId))
                .isEqualTo(memberId);
        assertThat(currentString("content", commentId))
                .isEqualTo("보존할 댓글");
    }

    @Test
    void rollsBackSoftDeleteWhenMetricsQueryFails() {
        Long memberId = insertMember();
        Long postId = insertPost(memberId);
        Long commentId = insertComment(postId, memberId);
        when(clock.instant()).thenReturn(NOW);
        when(commentQueryRepository.findSnapshot(commentId))
                .thenReturn(Optional.of(new CommentSnapshot(
                        commentId,
                        postId,
                        memberId,
                        null
                )));
        when(commentQueryRepository.findPostMetrics(postId))
                .thenThrow(new IllegalStateException(
                        "metrics query failed"
                ));

        assertThatThrownBy(() -> commentCommandService.delete(
                memberId,
                commentId
        )).isInstanceOf(IllegalStateException.class);

        assertThat(currentInstant("deleted_at", commentId)).isNull();
    }

    private Long insertMember() {
        String suffix = UUID.randomUUID()
                .toString()
                .replace("-", "")
                .substring(0, 12);
        jdbcTemplate.update(
                """
                        INSERT INTO member (
                            email, password_hash, nickname, status
                        )
                        VALUES (?, 'encoded-password', ?, 'ACTIVE')
                        """,
                "comment-delete-" + suffix + "@example.com",
                "comment-delete-" + suffix
        );
        return jdbcTemplate.queryForObject(
                "SELECT id FROM member WHERE nickname = ?",
                Long.class,
                "comment-delete-" + suffix
        );
    }

    private Long insertPost(Long memberId) {
        jdbcTemplate.update(
                """
                        INSERT INTO post (
                            board_type, author_id, title, content,
                            status, is_auto_report, view_count
                        )
                        VALUES (
                            'FREE', ?, '댓글 삭제 테스트', '본문',
                            'ACTIVE', FALSE, 3
                        )
                        """,
                memberId
        );
        return jdbcTemplate.queryForObject(
                "SELECT id FROM post WHERE author_id = ?",
                Long.class,
                memberId
        );
    }

    private Long insertComment(Long postId, Long memberId) {
        jdbcTemplate.update(
                """
                        INSERT INTO post_comment (
                            post_id, author_id, content
                        )
                        VALUES (?, ?, '보존할 댓글')
                        """,
                postId,
                memberId
        );
        return jdbcTemplate.queryForObject(
                """
                        SELECT id
                        FROM post_comment
                        WHERE post_id = ?
                          AND author_id = ?
                        """,
                Long.class,
                postId,
                memberId
        );
    }

    private Instant currentInstant(String column, Long commentId) {
        return jdbcTemplate.queryForObject(
                "SELECT " + column + " FROM post_comment WHERE id = ?",
                (resultSet, rowNumber) -> {
                    java.sql.Timestamp timestamp =
                            resultSet.getTimestamp(column);
                    return timestamp == null
                            ? null
                            : timestamp.toInstant();
                },
                commentId
        );
    }

    private Long currentLong(String column, Long commentId) {
        return jdbcTemplate.queryForObject(
                "SELECT " + column + " FROM post_comment WHERE id = ?",
                Long.class,
                commentId
        );
    }

    private String currentString(String column, Long commentId) {
        return jdbcTemplate.queryForObject(
                "SELECT " + column + " FROM post_comment WHERE id = ?",
                String.class,
                commentId
        );
    }
}
