package com.ssafy.ssabangpalbang.community.service;

import com.ssafy.ssabangpalbang.community.dto.request.CommentCreateRequest;
import com.ssafy.ssabangpalbang.community.repository.CommentCommandRepository;
import com.ssafy.ssabangpalbang.community.repository.CommentQueryRepository;
import com.ssafy.ssabangpalbang.community.repository.PostQueryRepository;
import com.ssafy.ssabangpalbang.global.error.BusinessException;
import com.ssafy.ssabangpalbang.global.error.ErrorCode;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.Optional;
import java.util.UUID;
import java.time.Clock;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.when;

@DataJpaTest
@ActiveProfiles("test")
@Import(CommentCommandService.class)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@Sql(statements = {
        "DROP TABLE IF EXISTS post_comment",
        "DROP TABLE IF EXISTS post",
        "DROP TABLE IF EXISTS member",
        "CREATE TABLE member ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "email VARCHAR(255) NOT NULL UNIQUE, "
                + "password_hash VARCHAR(255), "
                + "nickname VARCHAR(50) NOT NULL UNIQUE, "
                + "profile_image_url VARCHAR(500), "
                + "selected_character_id VARCHAR(20) NOT NULL "
                + "DEFAULT 'PALBANG', "
                + "age_group VARCHAR(20), "
                + "age_group_public_agreed BOOLEAN NOT NULL DEFAULT FALSE, "
                + "service_notification_agreed BOOLEAN NOT NULL DEFAULT TRUE, "
                + "ad_notification_agreed BOOLEAN NOT NULL DEFAULT FALSE, "
                + "status VARCHAR(20) NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE post ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "board_type VARCHAR(20) NOT NULL, "
                + "author_id BIGINT, "
                + "title VARCHAR(200) NOT NULL, "
                + "content CLOB NOT NULL, "
                + "status VARCHAR(20) NOT NULL, "
                + "is_auto_report BOOLEAN NOT NULL, "
                + "report_id BIGINT, "
                + "apartment_id BIGINT, "
                + "view_count BIGINT NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE post_comment ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "post_id BIGINT NOT NULL, "
                + "author_id BIGINT NOT NULL, "
                + "content CLOB NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)"
})
@Sql(
        statements = {
                "DROP TABLE IF EXISTS post_comment",
                "DROP TABLE IF EXISTS post",
                "DROP TABLE IF EXISTS member"
        },
        executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD
)
class CommentCreateTransactionTest {

    @Autowired
    private CommentCommandService commentCommandService;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @MockitoBean
    private PostQueryRepository postQueryRepository;

    @MockitoBean
    private CommentCommandRepository commentCommandRepository;

    @MockitoBean
    private CommentQueryRepository commentQueryRepository;

    @MockitoBean
    private Clock clock;

    @Test
    void rollsBackInsertedCommentWhenMetricsQueryFails() {
        Long memberId = insertMember();
        Long postId = insertPost(memberId);
        when(postQueryRepository.findInteractions(postId, memberId))
                .thenThrow(new IllegalStateException(
                        "metrics query failed"
                ));

        assertThatThrownBy(() -> commentCommandService.create(
                memberId,
                postId,
                new CommentCreateRequest("롤백 대상 댓글")
        )).isInstanceOf(IllegalStateException.class);

        assertThat(commentCount(postId)).isZero();
    }

    @Test
    void rollsBackInsertedCommentWhenMetricsRowDisappears() {
        Long memberId = insertMember();
        Long postId = insertPost(memberId);
        when(postQueryRepository.findInteractions(postId, memberId))
                .thenReturn(Optional.empty());

        assertThatThrownBy(() -> commentCommandService.create(
                memberId,
                postId,
                new CommentCreateRequest("롤백 대상 댓글")
        )).isInstanceOfSatisfying(
                BusinessException.class,
                exception -> assertThat(exception.getErrorCode())
                        .isEqualTo(
                                ErrorCode.POST_NOT_FOUND
                        )
        );

        assertThat(commentCount(postId)).isZero();
    }

    private Long insertMember() {
        String suffix = UUID.randomUUID()
                .toString()
                .replace("-", "")
                .substring(0, 12);
        jdbcTemplate.update(
                """
                        INSERT INTO member (
                            email, password_hash, nickname, status
                        )
                        VALUES (?, 'encoded-password', ?, 'ACTIVE')
                        """,
                "comment-tx-" + suffix + "@example.com",
                "comment-tx-" + suffix
        );
        return jdbcTemplate.queryForObject(
                "SELECT id FROM member WHERE nickname = ?",
                Long.class,
                "comment-tx-" + suffix
        );
    }

    private Long insertPost(Long memberId) {
        jdbcTemplate.update(
                """
                        INSERT INTO post (
                            board_type, author_id, title, content,
                            status, is_auto_report, view_count
                        )
                        VALUES (
                            'FREE', ?, '댓글 테스트', '본문',
                            'ACTIVE', FALSE, 3
                        )
                        """,
                memberId
        );
        return jdbcTemplate.queryForObject(
                "SELECT id FROM post WHERE author_id = ?",
                Long.class,
                memberId
        );
    }

    private long commentCount(Long postId) {
        Long count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM post_comment WHERE post_id = ?",
                Long.class,
                postId
        );
        return count == null ? 0L : count;
    }
}
