package com.ssafy.ssabangpalbang.community.service;

import com.ssafy.ssabangpalbang.community.dto.response.PostDeleteResponse;
import com.ssafy.ssabangpalbang.community.repository.PostCommandRepository;
import com.ssafy.ssabangpalbang.community.repository.PostQueryRepository;
import com.ssafy.ssabangpalbang.community.repository.PostRepository;
import com.ssafy.ssabangpalbang.community.support.PostResponseAssembler;
import com.ssafy.ssabangpalbang.media.service.MediaFileQueryPort;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.Clock;
import java.time.Instant;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.when;

@DataJpaTest
@ActiveProfiles("test")
@Import(PostCommandService.class)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@Sql(statements = {
        "DROP TABLE IF EXISTS post_attachment",
        "DROP TABLE IF EXISTS post",
        "DROP TABLE IF EXISTS member",
        "CREATE TABLE member ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "email VARCHAR(255) NOT NULL UNIQUE, "
                + "password_hash VARCHAR(255), "
                + "nickname VARCHAR(50) NOT NULL UNIQUE, "
                + "profile_image_url VARCHAR(500), "
                + "selected_character_id VARCHAR(20) NOT NULL "
                + "DEFAULT 'PALBANG', "
                + "age_group VARCHAR(20), "
                + "age_group_public_agreed BOOLEAN NOT NULL DEFAULT FALSE, "
                + "service_notification_agreed BOOLEAN NOT NULL DEFAULT TRUE, "
                + "ad_notification_agreed BOOLEAN NOT NULL DEFAULT FALSE, "
                + "status VARCHAR(20) NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE post ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "board_type VARCHAR(20) NOT NULL, "
                + "author_id BIGINT, "
                + "title VARCHAR(200) NOT NULL, "
                + "content CLOB NOT NULL, "
                + "status VARCHAR(20) NOT NULL, "
                + "is_auto_report BOOLEAN NOT NULL, "
                + "report_id BIGINT, "
                + "apartment_id BIGINT, "
                + "view_count BIGINT NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE post_attachment ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "post_id BIGINT NOT NULL, "
                + "file_id BIGINT NOT NULL, "
                + "display_order INT NOT NULL, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)"
})
@Sql(
        statements = {
                "DROP TABLE IF EXISTS post_attachment",
                "DROP TABLE IF EXISTS post",
                "DROP TABLE IF EXISTS member"
        },
        executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD
)
class PostDeleteTransactionTest {

    private static final Instant NOW =
            Instant.parse("2026-07-29T08:00:00Z");

    @Autowired
    private PostCommandService postCommandService;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @MockitoSpyBean
    private PostRepository postRepository;

    @MockitoBean
    private PostQueryRepository postQueryRepository;

    @MockitoBean
    private PostCommandRepository postCommandRepository;

    @MockitoBean
    private MediaFileQueryPort mediaFileQueryPort;

    @MockitoBean
    private PostResponseAssembler postResponseAssembler;

    @MockitoBean
    private Clock clock;

    @Test
    void commitsOnlyPostTimestampsAndPreservesAttachment() {
        Long memberId = insertMember();
        Long postId = insertPost(memberId);
        insertAttachment(postId);
        when(clock.instant()).thenReturn(NOW);

        PostDeleteResponse response =
                postCommandService.delete(memberId, postId);

        assertThat(response.deletedAt().toInstant()).isEqualTo(NOW);
        assertThat(currentInstant("deleted_at", postId)).isEqualTo(NOW);
        assertThat(currentInstant("updated_at", postId)).isEqualTo(NOW);
        assertThat(currentString("status", postId)).isEqualTo("ACTIVE");
        assertThat(currentString("title", postId)).isEqualTo("기존 제목");
        assertThat(currentString("content", postId)).isEqualTo("기존 본문");
        assertThat(currentLong("view_count", postId)).isEqualTo(12L);
        assertThat(attachmentCount(postId)).isEqualTo(1L);
    }

    @Test
    void rollsBackSoftDeleteWhenFlushFails() {
        Long memberId = insertMember();
        Long postId = insertPost(memberId);
        when(clock.instant()).thenReturn(NOW);
        doThrow(new DataIntegrityViolationException("flush failed"))
                .when(postRepository)
                .flush();

        assertThatThrownBy(() ->
                postCommandService.delete(memberId, postId)
        ).isInstanceOf(DataIntegrityViolationException.class);

        assertThat(currentInstant("deleted_at", postId)).isNull();
        assertThat(currentString("status", postId)).isEqualTo("ACTIVE");
    }

    private Long insertMember() {
        String suffix = UUID.randomUUID()
                .toString()
                .replace("-", "")
                .substring(0, 12);
        String email = "post-delete-tx-" + suffix + "@example.com";
        jdbcTemplate.update(
                """
                        INSERT INTO member (
                            email, password_hash, nickname, status
                        )
                        VALUES (?, 'encoded-password', ?, 'ACTIVE')
                        """,
                email,
                "delete-tx-" + suffix
        );
        return jdbcTemplate.queryForObject(
                "SELECT id FROM member WHERE email = ?",
                Long.class,
                email
        );
    }

    private Long insertPost(Long memberId) {
        jdbcTemplate.update(
                """
                        INSERT INTO post (
                            board_type, author_id, title, content,
                            status, is_auto_report, apartment_id,
                            view_count
                        )
                        VALUES (
                            'FREE', ?, '기존 제목', '기존 본문',
                            'ACTIVE', FALSE, 15, 12
                        )
                        """,
                memberId
        );
        return jdbcTemplate.queryForObject(
                """
                        SELECT id
                        FROM post
                        WHERE author_id = ?
                        ORDER BY id DESC
                        LIMIT 1
                        """,
                Long.class,
                memberId
        );
    }

    private void insertAttachment(Long postId) {
        jdbcTemplate.update(
                """
                        INSERT INTO post_attachment (
                            post_id, file_id, display_order
                        )
                        VALUES (?, 401, 0)
                        """,
                postId
        );
    }

    private Instant currentInstant(String column, Long postId) {
        return jdbcTemplate.queryForObject(
                "SELECT " + column + " FROM post WHERE id = ?",
                Instant.class,
                postId
        );
    }

    private String currentString(String column, Long postId) {
        return jdbcTemplate.queryForObject(
                "SELECT " + column + " FROM post WHERE id = ?",
                String.class,
                postId
        );
    }

    private long currentLong(String column, Long postId) {
        Long value = jdbcTemplate.queryForObject(
                "SELECT " + column + " FROM post WHERE id = ?",
                Long.class,
                postId
        );
        return value == null ? 0L : value;
    }

    private long attachmentCount(Long postId) {
        Long count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM post_attachment WHERE post_id = ?",
                Long.class,
                postId
        );
        return count == null ? 0L : count;
    }
}
