package com.ssafy.ssabangpalbang.community.service;

import com.ssafy.ssabangpalbang.community.dto.request.PostUpdateRequest;
import com.ssafy.ssabangpalbang.community.repository.PostAttachmentRepository;
import com.ssafy.ssabangpalbang.community.repository.PostCommandRepository;
import com.ssafy.ssabangpalbang.community.repository.PostQueryRepository;
import com.ssafy.ssabangpalbang.community.support.PostResponseAssembler;
import com.ssafy.ssabangpalbang.global.error.BusinessException;
import com.ssafy.ssabangpalbang.global.error.ErrorCode;
import com.ssafy.ssabangpalbang.media.domain.FileUsage;
import com.ssafy.ssabangpalbang.media.domain.UploadStatus;
import com.ssafy.ssabangpalbang.media.service.MediaFileQueryPort;
import com.ssafy.ssabangpalbang.media.service.MediaFileSnapshot;
import org.hibernate.exception.ConstraintViolationException;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.sql.SQLException;
import java.time.Clock;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.when;

@DataJpaTest
@ActiveProfiles("test")
@Import(PostCommandService.class)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@Sql(statements = {
        "DROP TABLE IF EXISTS post_attachment",
        "DROP TABLE IF EXISTS post",
        "DROP TABLE IF EXISTS member",
        "CREATE TABLE member ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "email VARCHAR(255) NOT NULL UNIQUE, "
                + "password_hash VARCHAR(255), "
                + "nickname VARCHAR(50) NOT NULL UNIQUE, "
                + "profile_image_url VARCHAR(500), "
                + "selected_character_id VARCHAR(20) NOT NULL "
                + "DEFAULT 'PALBANG', "
                + "age_group VARCHAR(20), "
                + "age_group_public_agreed BOOLEAN NOT NULL DEFAULT FALSE, "
                + "service_notification_agreed BOOLEAN NOT NULL DEFAULT TRUE, "
                + "ad_notification_agreed BOOLEAN NOT NULL DEFAULT FALSE, "
                + "status VARCHAR(20) NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE post ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "board_type VARCHAR(20) NOT NULL, "
                + "author_id BIGINT, "
                + "title VARCHAR(200) NOT NULL, "
                + "content CLOB NOT NULL, "
                + "status VARCHAR(20) NOT NULL, "
                + "is_auto_report BOOLEAN NOT NULL, "
                + "report_id BIGINT, "
                + "apartment_id BIGINT, "
                + "view_count BIGINT NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP)",
        "CREATE TABLE post_attachment ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "post_id BIGINT NOT NULL, "
                + "file_id BIGINT NOT NULL, "
                + "display_order INT NOT NULL, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "CONSTRAINT uq_post_attachment_file UNIQUE (file_id), "
                + "CONSTRAINT uq_post_attachment_post_file "
                + "UNIQUE (post_id, file_id), "
                + "CONSTRAINT uq_post_attachment_post_order "
                + "UNIQUE (post_id, display_order))"
})
@Sql(
        statements = {
                "DROP TABLE IF EXISTS post_attachment",
                "DROP TABLE IF EXISTS post",
                "DROP TABLE IF EXISTS member"
        },
        executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD
)
class PostUpdateTransactionTest {

    private static final Instant NOW =
            Instant.parse("2026-07-29T07:50:00Z");

    @Autowired
    private PostCommandService postCommandService;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @MockitoSpyBean
    private PostAttachmentRepository postAttachmentRepository;

    @MockitoBean
    private PostQueryRepository postQueryRepository;

    @MockitoBean
    private PostCommandRepository postCommandRepository;

    @MockitoBean
    private MediaFileQueryPort mediaFileQueryPort;

    @MockitoBean
    private PostResponseAssembler postResponseAssembler;

    @MockitoBean
    private Clock clock;

    @Test
    void rollsBackPostFieldsWhenAttachmentFlushFails() {
        Long memberId = insertMember();
        Long postId = insertPost(memberId);
        when(clock.instant()).thenReturn(NOW);
        when(mediaFileQueryPort.findAllByIdInForUpdate(List.of(401L)))
                .thenReturn(List.of(new MediaFileSnapshot(
                        401L,
                        memberId,
                        FileUsage.POST_ATTACHMENT,
                        "attachment.jpg",
                        "image/jpeg",
                        UploadStatus.COMPLETED,
                        null,
                        null
                )));

        AtomicInteger flushCount = new AtomicInteger();
        doAnswer(invocation -> {
            if (flushCount.incrementAndGet() == 2) {
                throw attachmentUniqueViolation();
            }
            return null;
        }).when(postAttachmentRepository).flush();

        PostUpdateRequest request = new PostUpdateRequest();
        request.setTitle("변경 제목");
        request.setFileIds(List.of(401L));

        assertThatThrownBy(() -> postCommandService.update(
                memberId,
                postId,
                request
        )).isInstanceOfSatisfying(
                BusinessException.class,
                exception -> assertThat(exception.getErrorCode())
                        .isEqualTo(
                                ErrorCode.POST_ATTACHMENT_ALREADY_USED
                        )
        );

        assertThat(currentTitle(postId)).isEqualTo("기존 제목");
        assertThat(attachmentCount(postId)).isZero();
    }

    private Long insertMember() {
        String suffix = UUID.randomUUID()
                .toString()
                .replace("-", "")
                .substring(0, 12);
        String email = "post-update-tx-" + suffix + "@example.com";
        jdbcTemplate.update(
                """
                        INSERT INTO member (
                            email, password_hash, nickname, status
                        )
                        VALUES (?, 'encoded-password', ?, 'ACTIVE')
                        """,
                email,
                "update-tx-" + suffix
        );
        return jdbcTemplate.queryForObject(
                "SELECT id FROM member WHERE email = ?",
                Long.class,
                email
        );
    }

    private Long insertPost(Long memberId) {
        jdbcTemplate.update(
                """
                        INSERT INTO post (
                            board_type, author_id, title, content,
                            status, is_auto_report, view_count
                        )
                        VALUES (
                            'FREE', ?, '기존 제목', '기존 본문',
                            'ACTIVE', FALSE, 0
                        )
                        """,
                memberId
        );
        return jdbcTemplate.queryForObject(
                """
                        SELECT id
                        FROM post
                        WHERE author_id = ?
                        ORDER BY id DESC
                        LIMIT 1
                        """,
                Long.class,
                memberId
        );
    }

    private String currentTitle(Long postId) {
        return jdbcTemplate.queryForObject(
                "SELECT title FROM post WHERE id = ?",
                String.class,
                postId
        );
    }

    private long attachmentCount(Long postId) {
        Long count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM post_attachment WHERE post_id = ?",
                Long.class,
                postId
        );
        return count == null ? 0L : count;
    }

    private DataIntegrityViolationException attachmentUniqueViolation() {
        ConstraintViolationException cause =
                new ConstraintViolationException(
                        "constraint violation",
                        new SQLException("duplicate"),
                        "uq_post_attachment_file"
                );
        return new DataIntegrityViolationException(
                "could not execute statement",
                cause
        );
    }
}
