package com.ssafy.ssabangpalbang.apartment.repository;

import com.ssafy.ssabangpalbang.apartment.domain.ApartmentFavorite;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@ActiveProfiles("test")
@Sql(statements = {
        "DROP TABLE IF EXISTS apartment_favorite",
        "CREATE TABLE apartment_favorite ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "member_id BIGINT NOT NULL, "
                + "apartment_id BIGINT NOT NULL, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL)",
        "INSERT INTO apartment_favorite "
                + "(id, member_id, apartment_id, created_at) "
                + "VALUES (1, 1, 10, "
                + "TIMESTAMP WITH TIME ZONE '2026-07-20 10:00:00+09:00')",
        "INSERT INTO apartment_favorite "
                + "(id, member_id, apartment_id, created_at) "
                + "VALUES (2, 1, 20, "
                + "TIMESTAMP WITH TIME ZONE '2026-07-22 10:00:00+09:00')",
        "INSERT INTO apartment_favorite "
                + "(id, member_id, apartment_id, created_at) "
                + "VALUES (3, 1, 30, "
                + "TIMESTAMP WITH TIME ZONE '2026-07-22 10:00:00+09:00')",
        "INSERT INTO apartment_favorite "
                + "(id, member_id, apartment_id, created_at) "
                + "VALUES (4, 2, 40, "
                + "TIMESTAMP WITH TIME ZONE '2026-07-23 10:00:00+09:00')"
})
class ApartmentFavoriteListRepositoryTest {

    @Autowired
    private ApartmentFavoriteRepository repository;

    @Test
    void 회원별_최근_찜_순과_id_동률_정렬로_페이지를_조회한다() {
        Page<ApartmentFavorite> first =
                repository.findByMemberIdOrderByCreatedAtDescIdDesc(
                        1L,
                        PageRequest.of(0, 2)
                );
        Page<ApartmentFavorite> second =
                repository.findByMemberIdOrderByCreatedAtDescIdDesc(
                        1L,
                        PageRequest.of(1, 2)
                );

        assertThat(first.getContent())
                .extracting(ApartmentFavorite::getApartmentId)
                .containsExactly(30L, 20L);
        assertThat(second.getContent())
                .extracting(ApartmentFavorite::getApartmentId)
                .containsExactly(10L);
        assertThat(first.getTotalElements()).isEqualTo(3);
        assertThat(first.getTotalPages()).isEqualTo(2);
    }
}
