package com.ssafy.ssabangpalbang.fieldvisit.stt.integration;

import com.ssafy.ssabangpalbang.fieldvisit.stt.domain.SttJob;
import com.ssafy.ssabangpalbang.fieldvisit.stt.domain.SttJobAttempt;
import com.ssafy.ssabangpalbang.fieldvisit.stt.domain.SttStatus;
import com.ssafy.ssabangpalbang.fieldvisit.stt.repository.SttJobAttemptRepository;
import com.ssafy.ssabangpalbang.fieldvisit.stt.repository.SttJobRepository;
import com.ssafy.ssabangpalbang.fieldvisit.stt.repository.SttAudioCleanupJobRepository;
import com.ssafy.ssabangpalbang.fieldvisit.stt.service.SttFailureResult;
import com.ssafy.ssabangpalbang.fieldvisit.stt.service.SttProcessingResult;
import com.ssafy.ssabangpalbang.fieldvisit.stt.service.SttResultHandler;
import com.ssafy.ssabangpalbang.fieldvisit.stt.service.SttSuccessResult;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doThrow;

@SpringBootTest(properties = {
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "spring.flyway.enabled=false"
})
@ActiveProfiles("test")
class SttResultHandlerIntegrationTest {

    private static final Long MEMBER_ID = 7L;
    private static final Long STUDY_ID = 10L;
    private static final Long SESSION_ID = 100L;
    private static final Long AUDIO_FILE_ID = 90L;
    private static final Long CHECKLIST_ITEM_ID = 503L;
    private static final String STT_ID = "stt-result";
    private static final OffsetDateTime REQUESTED_AT = OffsetDateTime.of(
            2026,
            7,
            25,
            14,
            25,
            0,
            0,
            ZoneOffset.ofHours(9)
    );
    private static final OffsetDateTime COMPLETED_AT =
            REQUESTED_AT.plusSeconds(8);

    @Autowired
    private SttResultHandler resultHandler;

    @Autowired
    private SttJobRepository sttJobRepository;

    @Autowired
    private SttJobAttemptRepository sttJobAttemptRepository;

    @Autowired
    private JdbcClient jdbcClient;

    @MockitoSpyBean
    private SttAudioCleanupJobRepository cleanupJobRepository;

    @BeforeEach
    void createResultTables() {
        jdbcClient.sql("""
                        CREATE TABLE IF NOT EXISTS file_meta (
                            id BIGINT PRIMARY KEY,
                            owner_id BIGINT NOT NULL,
                            study_id BIGINT,
                            file_usage VARCHAR(30) NOT NULL,
                            s3_key VARCHAR(500) NOT NULL,
                            upload_status VARCHAR(20) NOT NULL,
                            deleted_at TIMESTAMP WITH TIME ZONE,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL
                        )
                        """).update();
        jdbcClient.sql("""
                        CREATE TABLE IF NOT EXISTS field_record (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            session_id BIGINT NOT NULL,
                            checklist_item_id BIGINT NOT NULL,
                            author_id BIGINT NOT NULL,
                            source_type VARCHAR(20) NOT NULL,
                            text_content VARCHAR(2000),
                            stt_status VARCHAR(20),
                            client_request_id VARCHAR(100) UNIQUE NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL
                        )
                        """).update();
        jdbcClient.sql("""
                        INSERT INTO file_meta(
                            id,
                            owner_id,
                            study_id,
                            file_usage,
                            s3_key,
                            upload_status,
                            deleted_at,
                            created_at
                        ) VALUES (
                            :id,
                            :ownerId,
                            :studyId,
                            'STT_AUDIO',
                            :objectKey,
                            'COMPLETED',
                            NULL,
                            :createdAt
                        )
                        """)
                .param("id", AUDIO_FILE_ID)
                .param("ownerId", MEMBER_ID)
                .param("studyId", STUDY_ID)
                .param("objectKey", "stt/audio.webm")
                .param("createdAt", REQUESTED_AT)
                .update();
    }

    @AfterEach
    void cleanUp() {
        cleanupJobRepository.deleteAll();
        sttJobAttemptRepository.deleteAll();
        sttJobRepository.deleteAll();
        jdbcClient.sql("DELETE FROM field_record").update();
        jdbcClient.sql("DELETE FROM file_meta").update();
    }

    @Test
    void 처리_시작은_job과_attempt를_PROCESSING으로_전이한다() {
        SttJob job = persistPendingJob();
        OffsetDateTime startedAt = REQUESTED_AT.plusSeconds(2);

        SttResultHandler.HandlingOutcome first =
                resultHandler.markProcessing(new SttProcessingResult(
                        STT_ID,
                        1,
                        startedAt
                ));
        SttResultHandler.HandlingOutcome duplicate =
                resultHandler.markProcessing(new SttProcessingResult(
                        STT_ID,
                        1,
                        startedAt.plusSeconds(1)
                ));

        assertThat(first).isEqualTo(SttResultHandler.HandlingOutcome.APPLIED);
        assertThat(duplicate).isEqualTo(
                SttResultHandler.HandlingOutcome.IGNORED_DUPLICATE
        );
        SttJob processing = sttJobRepository.findById(job.getId())
                .orElseThrow();
        assertThat(processing.getStatus()).isEqualTo(SttStatus.PROCESSING);
        assertThat(processing.getStartedAt()).isEqualTo(startedAt);
        SttJobAttempt attempt = sttJobAttemptRepository
                .findTopBySttJobIdOrderByAttemptNoDesc(job.getId())
                .orElseThrow();
        assertThat(attempt.getStatus()).isEqualTo(SttStatus.PROCESSING);
        assertThat(attempt.getStartedAt()).isEqualTo(startedAt);
    }

    @Test
    void 현재_attempt_성공은_기록_한_건과_원본_접근_차단을_커밋한다() {
        SttJob job = persistPendingJob();

        SttResultHandler.HandlingOutcome first = resultHandler.handleSuccess(
                new SttSuccessResult(
                        STT_ID,
                        1,
                        "역에서 단지 입구까지 경사가 있습니다.",
                        COMPLETED_AT
                )
        );
        SttResultHandler.HandlingOutcome duplicate =
                resultHandler.handleSuccess(new SttSuccessResult(
                        STT_ID,
                        1,
                        "중복 결과",
                        COMPLETED_AT.plusSeconds(1)
                ));

        assertThat(first).isEqualTo(SttResultHandler.HandlingOutcome.APPLIED);
        assertThat(duplicate).isEqualTo(
                SttResultHandler.HandlingOutcome.IGNORED_DUPLICATE
        );

        SttJob completed = sttJobRepository.findById(job.getId())
                .orElseThrow();
        assertThat(completed.getStatus()).isEqualTo(SttStatus.DONE);
        assertThat(completed.getFieldRecordId()).isNotNull();
        assertThat(completed.getSessionId()).isEqualTo(SESSION_ID);
        assertThat(completed.getChecklistItemId())
                .isEqualTo(CHECKLIST_ITEM_ID);
        assertThat(completed.getMemberId()).isEqualTo(MEMBER_ID);
        assertThat(sttJobAttemptRepository
                .findTopBySttJobIdOrderByAttemptNoDesc(job.getId()))
                .get()
                .extracting(SttJobAttempt::getStatus)
                .isEqualTo(SttStatus.DONE);

        Map<String, Object> fieldRecord = jdbcClient.sql("""
                        SELECT session_id,
                               checklist_item_id,
                               author_id,
                               source_type,
                               text_content,
                               stt_status,
                               client_request_id
                        FROM field_record
                        """)
                .query()
                .singleRow();
        assertThat(fieldRecord)
                .containsEntry("SESSION_ID", SESSION_ID)
                .containsEntry("CHECKLIST_ITEM_ID", CHECKLIST_ITEM_ID)
                .containsEntry("AUTHOR_ID", MEMBER_ID)
                .containsEntry("SOURCE_TYPE", "STT")
                .containsEntry(
                        "TEXT_CONTENT",
                        "역에서 단지 입구까지 경사가 있습니다."
                )
                .containsEntry("STT_STATUS", "DONE")
                .containsEntry("CLIENT_REQUEST_ID", "STT:" + STT_ID);
        assertThat(jdbcClient.sql(
                        "SELECT COUNT(*) FROM field_record"
                ).query(Long.class).single())
                .isEqualTo(1L);

        Map<String, Object> audio = jdbcClient.sql("""
                        SELECT upload_status, deleted_at
                        FROM file_meta
                        WHERE id = :audioFileId
                        """)
                .param("audioFileId", AUDIO_FILE_ID)
                .query()
                .singleRow();
        assertThat(audio.get("UPLOAD_STATUS")).isEqualTo("DELETED");
        assertThat(audio.get("DELETED_AT")).isNotNull();
        assertThat(cleanupJobRepository.count()).isEqualTo(1);
        assertThat(cleanupJobRepository.findByAudioFileId(AUDIO_FILE_ID))
                .get()
                .satisfies(cleanup -> {
                    assertThat(cleanup.getObjectKey())
                            .isEqualTo("stt/audio.webm");
                    assertThat(cleanup.getAttemptCount()).isZero();
                    assertThat(cleanup.getNextAttemptAt())
                            .isAfter(COMPLETED_AT);
                });
    }

    @Test
    void cleanup_저장에_실패하면_기록_파일_job_attempt를_모두_롤백한다() {
        persistPendingJob();
        doThrow(new DataIntegrityViolationException("cleanup insert failed"))
                .when(cleanupJobRepository)
                .save(any());

        assertThatThrownBy(() -> resultHandler.handleSuccess(
                new SttSuccessResult(
                        STT_ID,
                        1,
                        "롤백되어야 하는 STT 원문",
                        COMPLETED_AT
                )
        )).isInstanceOf(DataIntegrityViolationException.class);

        assertThat(jdbcClient.sql("""
                        SELECT status FROM stt_job WHERE stt_id = :sttId
                        """)
                .param("sttId", STT_ID)
                .query(String.class)
                .single()).isEqualTo("PENDING");
        assertThat(jdbcClient.sql("""
                        SELECT status
                        FROM stt_job_attempt
                        WHERE stt_job_id = (
                            SELECT id FROM stt_job WHERE stt_id = :sttId
                        )
                        """)
                .param("sttId", STT_ID)
                .query(String.class)
                .single()).isEqualTo("PENDING");
        assertThat(jdbcClient.sql(
                        "SELECT COUNT(*) FROM field_record"
                ).query(Long.class).single())
                .isZero();
        assertThat(audioStatus()).isEqualTo("COMPLETED");
        assertThat(cleanupJobRepository.count()).isZero();
    }

    @Test
    void 오래된_attempt_성공은_job_기록_파일을_변경하지_않는다() {
        SttJob job = persistRetriedJob();

        SttResultHandler.HandlingOutcome outcome =
                resultHandler.handleSuccess(new SttSuccessResult(
                        STT_ID,
                        1,
                        null,
                        COMPLETED_AT
                ));

        assertThat(outcome)
                .isEqualTo(SttResultHandler.HandlingOutcome.IGNORED_STALE);
        assertThat(sttJobRepository.findById(job.getId()).orElseThrow()
                .getStatus()).isEqualTo(SttStatus.PENDING);
        assertThat(jdbcClient.sql(
                        "SELECT COUNT(*) FROM field_record"
                ).query(Long.class).single())
                .isZero();
        assertThat(audioStatus()).isEqualTo("COMPLETED");
        assertThat(cleanupJobRepository.count()).isZero();
    }

    @Test
    void 미래_attempt_결과는_계약_오류로_무시한다() {
        persistRetriedJob();

        SttResultHandler.HandlingOutcome outcome =
                resultHandler.handleFailure(new SttFailureResult(
                        STT_ID,
                        3,
                        "FUTURE",
                        "미래 attempt",
                        true,
                        COMPLETED_AT
                ));

        assertThat(outcome)
                .isEqualTo(SttResultHandler.HandlingOutcome.IGNORED_FUTURE);
        assertThat(sttJobRepository.findBySttId(STT_ID).orElseThrow()
                .getStatus()).isEqualTo(SttStatus.PENDING);
        assertThat(audioStatus()).isEqualTo("COMPLETED");
    }

    @Test
    void 현재_attempt_실패는_실패_정보만_갱신하고_원본을_보존한다() {
        SttJob job = persistPendingJob();

        SttResultHandler.HandlingOutcome outcome =
                resultHandler.handleFailure(new SttFailureResult(
                        STT_ID,
                        1,
                        "AI_TEMPORARY_ERROR",
                        "일시적인 처리 실패",
                        true,
                        COMPLETED_AT
                ));

        assertThat(outcome).isEqualTo(
                SttResultHandler.HandlingOutcome.APPLIED
        );
        SttJob failed = sttJobRepository.findById(job.getId()).orElseThrow();
        assertThat(failed.getStatus()).isEqualTo(SttStatus.FAILED);
        assertThat(failed.getFailCode()).isEqualTo("AI_TEMPORARY_ERROR");
        assertThat(failed.getFailReason()).isEqualTo("일시적인 처리 실패");
        assertThat(failed.isRetryable()).isTrue();
        assertThat(audioStatus()).isEqualTo("COMPLETED");
        assertThat(jdbcClient.sql(
                        "SELECT COUNT(*) FROM field_record"
                ).query(Long.class).single())
                .isZero();
        assertThat(cleanupJobRepository.count()).isZero();
    }

    @Test
    void 원본이_먼저_논리_삭제돼도_현재_attempt_성공은_반영한다() {
        SttJob job = persistPendingJob();
        jdbcClient.sql("""
                        UPDATE file_meta
                        SET upload_status = 'DELETED',
                            deleted_at = :deletedAt
                        WHERE id = :audioFileId
                        """)
                .param("deletedAt", COMPLETED_AT.minusSeconds(1))
                .param("audioFileId", AUDIO_FILE_ID)
                .update();

        SttResultHandler.HandlingOutcome outcome =
                resultHandler.handleSuccess(new SttSuccessResult(
                        STT_ID,
                        1,
                        "삭제 경합 뒤에도 반영할 변환 결과",
                        COMPLETED_AT
                ));

        assertThat(outcome).isEqualTo(
                SttResultHandler.HandlingOutcome.APPLIED
        );
        assertThat(sttJobRepository.findById(job.getId()).orElseThrow()
                .getStatus()).isEqualTo(SttStatus.DONE);
        assertThat(jdbcClient.sql(
                        "SELECT COUNT(*) FROM field_record"
                ).query(Long.class).single())
                .isEqualTo(1L);
        assertThat(cleanupJobRepository.count()).isEqualTo(1);
    }

    private SttJob persistPendingJob() {
        SttJob job = sttJobRepository.saveAndFlush(SttJob.create(
                STT_ID,
                MEMBER_ID,
                STUDY_ID,
                SESSION_ID,
                AUDIO_FILE_ID,
                CHECKLIST_ITEM_ID,
                UUID.randomUUID(),
                REQUESTED_AT
        ));
        sttJobAttemptRepository.saveAndFlush(SttJobAttempt.initial(
                job.getId(),
                MEMBER_ID,
                UUID.randomUUID(),
                REQUESTED_AT
        ));
        return job;
    }

    private SttJob persistRetriedJob() {
        SttJob job = sttJobRepository.saveAndFlush(SttJob.create(
                STT_ID,
                MEMBER_ID,
                STUDY_ID,
                SESSION_ID,
                AUDIO_FILE_ID,
                CHECKLIST_ITEM_ID,
                UUID.randomUUID(),
                REQUESTED_AT
        ));
        job.fail(
                "AI_TEMPORARY_ERROR",
                "일시적인 처리 실패",
                true,
                REQUESTED_AT.plusSeconds(2)
        );
        job = sttJobRepository.saveAndFlush(job);

        SttJobAttempt initial = SttJobAttempt.initial(
                job.getId(),
                MEMBER_ID,
                UUID.randomUUID(),
                REQUESTED_AT
        );
        initial.fail(
                "AI_TEMPORARY_ERROR",
                "일시적인 처리 실패",
                REQUESTED_AT.plusSeconds(2)
        );
        sttJobAttemptRepository.saveAndFlush(initial);

        job.prepareRetry(REQUESTED_AT.plusSeconds(3));
        job = sttJobRepository.saveAndFlush(job);
        sttJobAttemptRepository.saveAndFlush(SttJobAttempt.retry(
                job.getId(),
                MEMBER_ID,
                UUID.randomUUID(),
                2,
                REQUESTED_AT.plusSeconds(3)
        ));
        return job;
    }

    private String audioStatus() {
        return jdbcClient.sql("""
                        SELECT upload_status
                        FROM file_meta
                        WHERE id = :audioFileId
                        """)
                .param("audioFileId", AUDIO_FILE_ID)
                .query(String.class)
                .single();
    }
}
