package com.ssafy.ssabangpalbang.community.repository;

import com.ssafy.ssabangpalbang.community.domain.PostAttachment;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DataJpaTest
@ActiveProfiles("test")
@Sql(statements = {
        "DROP TABLE IF EXISTS post_attachment",
        "CREATE TABLE post_attachment ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "post_id BIGINT NOT NULL, "
                + "file_id BIGINT NOT NULL, "
                + "display_order INT NOT NULL, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL "
                + "DEFAULT CURRENT_TIMESTAMP, "
                + "CONSTRAINT uq_post_attachment_file UNIQUE (file_id), "
                + "CONSTRAINT uq_post_attachment_post_file "
                + "UNIQUE (post_id, file_id), "
                + "CONSTRAINT uq_post_attachment_post_order "
                + "UNIQUE (post_id, display_order))"
})
@Sql(
        statements = "DROP TABLE IF EXISTS post_attachment",
        executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD
)
class PostAttachmentRepositoryTest {

    @Autowired
    private PostAttachmentRepository postAttachmentRepository;

    @Test
    void preventsOneFileFromBeingAttachedToMultiplePosts() {
        postAttachmentRepository.saveAndFlush(
                PostAttachment.create(154L, 401L, 0)
        );

        assertThatThrownBy(() -> postAttachmentRepository.saveAndFlush(
                PostAttachment.create(155L, 401L, 0)
        )).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void deletesBeforeRecreatingAttachmentsInNewOrder() {
        postAttachmentRepository.saveAllAndFlush(List.of(
                PostAttachment.create(154L, 401L, 0),
                PostAttachment.create(154L, 402L, 1)
        ));

        postAttachmentRepository.deleteAllByPostId(154L);
        postAttachmentRepository.flush();
        postAttachmentRepository.saveAllAndFlush(List.of(
                PostAttachment.create(154L, 402L, 0),
                PostAttachment.create(154L, 401L, 1)
        ));

        assertThat(postAttachmentRepository
                .findAllByPostIdOrderByDisplayOrderAscIdAsc(154L))
                .extracting(PostAttachment::getFileId)
                .containsExactly(402L, 401L);
    }
}
