package com.ssafy.ssabangpalbang.study.service;

import com.ssafy.ssabangpalbang.notification.entity.Notification;
import com.ssafy.ssabangpalbang.notification.repository.NotificationCommandRepositoryImpl;
import com.ssafy.ssabangpalbang.notification.repository.NotificationRepository;
import com.ssafy.ssabangpalbang.study.event.StudySchedulePushRequestedEvent;
import com.ssafy.ssabangpalbang.study.repository.ScheduleReminderRow;
import com.ssafy.ssabangpalbang.study.service.port.StudyNotificationPort;
import com.ssafy.ssabangpalbang.study.service.port.StudyNotificationPortImpl;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.event.ApplicationEvents;
import org.springframework.test.context.event.RecordApplicationEvents;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

@DataJpaTest
@ActiveProfiles("test")
// NotificationCommandRepositoryImpl의 ON CONFLICT DO NOTHING은
// H2 기본 모드에서 문법 오류이므로 MODE=PostgreSQL H2를 명시한다.
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:study-schedule-reminder-writer;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
})
@Import({
        StudyScheduleReminderWriter.class,
        StudyNotificationPortImpl.class,
        NotificationCommandRepositoryImpl.class
})
@RecordApplicationEvents
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@Sql(statements = {
        "DROP TABLE IF EXISTS notification",
        "DROP TABLE IF EXISTS study_member",
        "DROP TABLE IF EXISTS member",
        "CREATE TABLE member ("
                + "id BIGINT PRIMARY KEY, "
                + "email VARCHAR(255) NOT NULL, "
                + "password_hash VARCHAR(255), "
                + "nickname VARCHAR(50) NOT NULL, "
                + "profile_image_url VARCHAR(500), "
                + "selected_character_id VARCHAR(20) NOT NULL, "
                + "age_group VARCHAR(20), "
                + "age_group_public_agreed BOOLEAN NOT NULL, "
                + "service_notification_agreed BOOLEAN NOT NULL, "
                + "ad_notification_agreed BOOLEAN NOT NULL, "
                + "status VARCHAR(20) NOT NULL, "
                + "deleted_at TIMESTAMP WITH TIME ZONE, "
                + "created_at TIMESTAMP WITH TIME ZONE NOT NULL, "
                + "updated_at TIMESTAMP WITH TIME ZONE NOT NULL)",
        "CREATE TABLE study_member ("
                + "id BIGINT PRIMARY KEY, "
                + "study_id BIGINT NOT NULL, "
                + "member_id BIGINT NOT NULL, "
                + "role VARCHAR(20) NOT NULL, "
                + "status VARCHAR(20) NOT NULL, "
                + "joined_at TIMESTAMP WITH TIME ZONE NOT NULL, "
                + "left_at TIMESTAMP WITH TIME ZONE, "
                + "chat_push_enabled BOOLEAN NOT NULL DEFAULT TRUE)",
        "CREATE TABLE notification ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "recipient_id BIGINT NOT NULL, "
                + "actor_id BIGINT, "
                + "category VARCHAR(30) NOT NULL, "
                + "type VARCHAR(30) NOT NULL, "
                + "target_screen VARCHAR(50), "
                + "target_id BIGINT, "
                + "target_sub_id BIGINT, "
                + "title VARCHAR(200), "
                + "body VARCHAR(500), "
                + "send_status VARCHAR(20), "
                + "fail_reason VARCHAR(255), "
                + "is_read BOOLEAN NOT NULL DEFAULT FALSE, "
                + "read_at TIMESTAMP WITH TIME ZONE, "
                + "idempotency_key VARCHAR(200) NOT NULL UNIQUE, "
                + "sent_at TIMESTAMP WITH TIME ZONE NOT NULL)"
})
class StudyScheduleReminderWriterTest {

    private static final Instant START_AT =
            Instant.parse("2026-08-02T00:00:00Z");

    @Autowired
    private StudyScheduleReminderWriter writer;
    @Autowired
    private StudyNotificationPort notificationPort;
    @Autowired
    private NotificationRepository notificationRepository;
    @Autowired
    private JdbcTemplate jdbcTemplate;
    @Autowired
    private ApplicationEvents applicationEvents;

    @Test
    void R1_같은_시각으로_2회_실행해도_수신자당_1건이다() {
        insertMember(1L);

        var first = writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));
        var second = writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));

        assertThat(first.createdNotifications()).isEqualTo(1);
        assertThat(second.createdNotifications()).isZero();
        assertThat(second.skippedDuplicates()).isEqualTo(1);
        assertThat(notificationRepository.count()).isEqualTo(1);
    }

    @Test
    void R2_같은_시각으로_5회_실행해도_수신자당_1건이다() {
        insertMember(1L);

        for (int count = 0; count < 5; count++) {
            writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));
        }

        assertThat(notificationRepository.count()).isEqualTo(1);
    }

    @Test
    void R3_시작_시각을_앞당기면_새_알림이_추가된다() {
        insertMember(1L);

        writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));
        writer.sendForSchedule(row(START_AT.minusSeconds(7200), "옥수역", "스터디"));

        assertThat(notificationRepository.count()).isEqualTo(2);
    }

    @Test
    void R4_시작_시각을_원래대로_되돌리면_추가되지_않는다() {
        insertMember(1L);

        writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));
        writer.sendForSchedule(row(START_AT.minusSeconds(7200), "옥수역", "스터디"));
        writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));

        assertThat(notificationRepository.count()).isEqualTo(2);
    }

    @Test
    void R5_멱등키는_일정_수신자_시작시각으로_구성한다() {
        insertMember(1L);

        writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));

        assertThat(notificationRepository.findAll().get(0).getIdempotencyKey())
                .isEqualTo(
                        "STUDY_SCHEDULE_REMINDER:7:1:"
                                + START_AT.getEpochSecond()
                );
    }

    @Test
    void R6_수신자_A가_이미_발송됐어도_B는_새로_생성한다() {
        insertMember(1L);
        insertMember(2L);
        insertStudyMember(10L, 2L);
        notificationPort.notifyScheduleReminder(notification(1L, START_AT, "스터디", "옥수역"));

        var result = writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));

        assertThat(result.createdNotifications()).isEqualTo(1);
        assertThat(result.skippedDuplicates()).isEqualTo(1);
        assertThat(notificationRepository.findAll())
                .extracting(Notification::getRecipientId)
                .containsExactlyInAnyOrder(1L, 2L);
    }

    @Test
    void R7_멱등키_충돌은_예외가_밖으로_나오지_않는다() {
        insertMember(1L);
        writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));

        assertThatCode(() -> writer.sendForSchedule(
                row(START_AT, "옥수역", "스터디")
        )).doesNotThrowAnyException();
    }

    @Test
    void R8_중복_수신자는_Push_이벤트를_다시_발행하지_않는다() {
        insertMember(1L);
        writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));
        long eventsBeforeDuplicate = reminderEventCount();

        writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));

        assertThat(reminderEventCount()).isEqualTo(eventsBeforeDuplicate);
    }

    @Test
    void R9_정상_저장된_수신자는_Push_이벤트를_정확히_1회_발행한다() {
        insertMember(1L);

        writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));

        assertThat(reminderEventCount()).isEqualTo(1);
    }

    @Test
    void R10_알림_행_필드가_정본과_일치한다() {
        insertMember(1L);

        writer.sendForSchedule(row(START_AT, "옥수역", "스터디"));

        Notification saved = notificationRepository.findAll().get(0);
        assertThat(saved.getActorId()).isNull();
        assertThat(saved.getType()).isEqualTo("STUDY_SCHEDULE_REMINDER");
        assertThat(saved.getCategory().name()).isEqualTo("STUDY");
        assertThat(saved.getTargetId()).isEqualTo(10L);
        assertThat(saved.getTargetSubId()).isEqualTo(7L);
    }

    @Test
    void R11_긴_스터디_제목의_body는_500자로_잘린다() {
        insertMember(1L);

        writer.sendForSchedule(row(
                START_AT,
                "옥수역",
                "가".repeat(600)
        ));

        assertThat(notificationRepository.findAll().get(0).getBody()).hasSize(500);
    }

    @Test
    void R12_장소가_null이면_장소_없는_문장을_만든다() {
        insertMember(1L);

        writer.sendForSchedule(row(START_AT, null, "검증 스터디"));

        assertThat(notificationRepository.findAll().get(0).getBody())
                .isEqualTo(
                        "'검증 스터디' 임장이 8월 2일 오전 9시 00분에 시작해요."
                );
    }

    private void insertMember(Long memberId) {
        jdbcTemplate.update(
                """
                INSERT INTO member (
                    id, email, nickname, selected_character_id,
                    age_group_public_agreed, service_notification_agreed,
                    ad_notification_agreed, status, created_at, updated_at
                ) VALUES (?, ?, ?, 'PALBANG', FALSE, TRUE, FALSE,
                          'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
                """,
                memberId,
                "member" + memberId + "@example.com",
                "member" + memberId
        );
    }

    private void insertStudyMember(Long id, Long memberId) {
        jdbcTemplate.update(
                """
                INSERT INTO study_member (
                    id, study_id, member_id, role, status, joined_at
                ) VALUES (?, 10, ?, 'MEMBER', 'ACTIVE', CURRENT_TIMESTAMP)
                """,
                id,
                memberId
        );
    }

    private ScheduleReminderRow row(
            Instant startAt,
            String meetingPlace,
            String studyTitle
    ) {
        return new TestScheduleReminderRow(
                7L,
                10L,
                studyTitle,
                1L,
                startAt,
                meetingPlace
        );
    }

    private StudyNotificationPort.ScheduleNotification notification(
            Long recipientId,
            Instant startAt,
            String studyTitle,
            String meetingPlace
    ) {
        return new StudyNotificationPort.ScheduleNotification(
                recipientId,
                null,
                10L,
                7L,
                studyTitle,
                "2026-08-02T09:00:00+09:00",
                meetingPlace,
                startAt.getEpochSecond(),
                true
        );
    }

    private long reminderEventCount() {
        return applicationEvents.stream(StudySchedulePushRequestedEvent.class)
                .count();
    }

    private record TestScheduleReminderRow(
            Long scheduleId,
            Long studyId,
            String studyTitle,
            Long leaderId,
            Instant startAt,
            String meetingPlace
    ) implements ScheduleReminderRow {

        @Override
        public Long getScheduleId() {
            return scheduleId;
        }

        @Override
        public Long getStudyId() {
            return studyId;
        }

        @Override
        public String getStudyTitle() {
            return studyTitle;
        }

        @Override
        public Long getLeaderId() {
            return leaderId;
        }

        @Override
        public Instant getStartAt() {
            return startAt;
        }

        @Override
        public String getMeetingPlace() {
            return meetingPlace;
        }
    }
}
